apiVersion: apps/v1beta1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: struct-deployment
spec:
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: structapp
    spec:
      containers:
      - name: structapp
        image: ubuntu:16.04
        volumeMounts:
        - name: ws
          mountPath: /mnt
        command: [ "/bin/bash", "-c"]
        args: ["apt-get update -y && apt-get install -y make gcc wget && wget  https://web.stanford.edu/group/pritchardlab/structure_software/release_versions/v2.3.4/structure_kernel_source.tar && tar -xvzf structure_kernel_source.tar && cd structure_kernel_src && make && touch /tmp/samplews.txt && sleep 300"]
      volumes:
      - name: ws
        hostPath:
            path: /tmp
